### PR TITLE
add task count route

### PR DESCRIPTION
**Pull request by jameslaneconkling**
backend route addition for [Tasks view should show "tasks remaining" count](https://github.com/orma/openroads-vn-analytics/issues/224).

cc @mileswwatkins

### CODE REVIEW

**Comment by jameslaneconkling** [comment]
note: `apiVersion` in jsDoc [is empty](https://github.com/orma/openroads-vn-api/pull/68/files#diff-4934f51d056657c0a24418e73bbe7884R165).  How are we versioning this?

**Comment by mileswwatkins** [comment]
Versioning is currently used only in the `package.json`: https://github.com/orma/openroads-vn-api/blob/develop/package.json#L3; we need to bump that version whenever a new deploy is made (from `develop` to `master`).

We only have one version of the API deployed, and only one version of the API docs deployed, so I don't think the `apiVersion` field is particularly useful to the docs. For now, you can use the same `0.3.0` value that Derek used.

**Comment by jameslaneconkling** [comment]
@mileswwatkins added api version.  how's it look?

**Comment by mileswwatkins** [comment]
Great!

**Pull request merged**
