### PR TITLE
[ready] Feature/stats endpoint

### PR DESCRIPTION
**Pull request by geohacker**
Fixes: https://github.com/orma/openroads-vn-analytics/issues/463
todo:

* [x] lengths
* [x] review status
* [x] province and district filter

cc @danielfdsilva @batpad

### CODE REVIEW

**Comment by geohacker** [comment]
@danielfdsilva this is ready if you'd like to test. The format I'm following is a bit different from what you proposed but achieves the same outcomes:

* /admin/stats

```
{
  "provinces": [
    {
      "id": 401,
      "code": "21",
      "parent_id": null,
      "name_en": "Thanh Hoa",
      "name_vn": "",
      "type": "province",
      "total": 8061.86316979538,
      "vpromm": 7979.64784915531,
      "districts": [
        {
          "id": 40101,
          "code": "TH",
          "parent_id": 401,
          "name_en": "Thanh Hoa City",
          "name_vn": "",
          "type": "district",
          "total": 5.94414146746047,
          "vpromm": 5.70325461874238,
          "status": {
            "pending": 263,
            "reviewed": 0
          } // continued all districts
        }
```

* /admin/stats?province=401
* /admin/stats?province=401&district=40101

These end points follow the same structure as above, but filter out content as they match.

**Comment by geohacker** [comment]
@danielfdsilva 'field data' is basically checking if the vpromm has associated OSM geometries. This has proved to be a misleading stat and also pretty complicated to make it part of the above end point, so i'm leaving that to be handled by the /total end point.

**Comment by danielfdsilva** [comment]
@geohacker That poses a problem since that endpoint (`/properties/roads/count`) returns the value for a given province or province + district. We'd need to make a lot of queries to get those values. It is one of the reasons why we added another endpoint for the stats.

Also, I've been looking into displaying the assets on the pages, but the province and district Id for the assets endpoint (`/properties/roads`) is different. Could we standardize this? Alternatively we need to add this (I guess it's osm id? right?) to the stats endpoint. Or do you have a better idea?

**Comment by geohacker** [comment]
@danielfdsilva just pushed a change that makes /properties/road/counts return everything like this:

```
{
  "count": 15401,
  "osmCount": 373,
  "province": {
    "21": {
      "count": 2871,
      "osmCount": 373,
      "district": {
        "TX": {
          "count": 56,
          "osmCount": 9
        },
        "TH": {
          "count": 59,
          "osmCount": 44
        }
```

This means that the return format for the entire endpoint has changed and is no longer backwards compatible. The province and district filters will continue to work.

**Comment by geohacker** [comment]
@danielfdsilva this is the stats end point PR. I will merge once you are able to test this locally. To have this run locally:

1. Run migrations - 
    * first https://github.com/orma/openroads-vn-api/pull/137/commits/2a4a00b6c51dbcbaa1c337e36b98b825e96e5ef5
    * and then https://github.com/orma/openroads-vn-api/pull/137/commits/fad87f39e4fc9b3dd516fe84942d9c371733180d
2. Start the server

**Pull request merged**
