### PR TITLE
Add new tables to database, and prepare for Dockerized deployment of database

### PR DESCRIPTION
**Pull request by mileswwatkins**
@dereklieu, can you look at the models that I added (the `db/sql/*.sql` outside of the core Macrocosm model `db/sql/macrocosm-db.sql`), and let me know if they look good to you? If so, merge in. I may also self-merge if I'm in a rush, but I'd still appreciate the eyes :)

closes https://github.com/orma/openroads-vn-analytics/issues/85

### CODE REVIEW

**Comment by dereklieu** [comment]
Would it be useful to have a `manual` or `other` field in addition to routeshoot and road lab pro? I see you added it in one and not the other.

**Comment by mileswwatkins** [comment]
I think that the field-collected geometries are okay to only include a list of the field-data sensors. This table will never see user-added information. That said, I could be convinced that this is overly prescriptive.

**Comment by mileswwatkins** [comment]
Also, I guess I have to update the Travis deployment to use ECS, too. Don't worry about merging yourself, then.

**Comment by scisco** [comment]
@mileswwatkins I'm working on this PR this morning. Don't merge.

**Comment by mileswwatkins** [comment]
Many thanks again, @scisco!

**Comment by scisco** [comment]
@mileswwatkins This is deployable with KES

Things added:

- Add circleci
- Remove travis
- KES stack for deployment user
- KES stack for iam roles
- KES stack for an ECS cluster with services set

The current repo uses node 5 which makes it incompatible with Kes. Kes requires node 6 or above.

Thus, I couldn't activate kes on circleci until the repo is upgraded to node 6 or above.

**Pull request merged**
